### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by pietvanzoen** [jeffkreeftmeijer/dolphin#1]
This is my first time playing with elixir so I'm having fun figuring things out. But it would be useful to outline some basic getting started instructions. This is where I got to so far:

install elixir:
```sh
brew install elixir
```

install web deps
```sh
cd assets
npm i
```

install elixir deps:
```sh
mix deps.get
```

start local server:
```sh
elixir -S mix phx.server
```

What I'm still figuring out is how to install/compile for production.

Perhaps a Makefile or similar would help with all this too? I'm not sure what's common with Elixir projects.

Thanks! Great project!

**Comment by pietvanzoen** [comment]
ah... looking at the procfile I guess this answers my question:

```sh
MIX_ENV=prod elixir --sname server -S mix phx.server
```

**Comment by jeffkreeftmeijer** [comment]
That's it! After installing the dependencies, you should be able to start the server by running `mix phx.server`. I've updated the README to include it.
